//! Chalk Core — SIS engine, OneRoster schema, data normalization, and database layer.

pub mod asset_csv;
pub mod attachments;
pub mod auth;
pub mod change_commit;
pub mod change_plan;
pub mod config;
pub mod connectors;
pub mod cookies;
pub mod crypto;
pub mod csv_import;
pub mod db;
pub mod email;
pub mod error;
pub mod http;
pub mod inbound_email;
pub mod jobs;
pub mod ldap;
pub mod mail;
pub mod migration;
pub mod models;
pub mod oneroster_csv;
pub mod passwords;
pub mod remote_write;
pub mod sync;
pub mod ticket_service;
pub mod totp;
pub mod webhooks;
